export const GET_INDEX_SUCCESS = 'GET_INDEX_SUCCESS'
export const GET_ARCHIVE_SUCCESS = 'GET_ARCHIVE_SUCCESS'
export const GET_SINGLE_SUCCESS = 'GET_SINGLE_SUCCESS'
export const GET_PAGE_SUCCESS = 'GET_PAGE_SUCCESS'

export const GET_ARCHIVE_CATCHED = 'GET_ARCHIVE_CATCHED'
export const GET_SINGLE_CATCHED = 'GET_SINGLE_CATCHED'
export const GET_PAGE_CATCHED = 'GET_PAGE_CATCHED'

export const GET_INDEX_FAILURE = 'GET_INDEX_FAILURE'
export const GET_ARCHIVE_FAILURE = 'GET_ARCHIVE_FAILURE'
export const GET_SINGLE_FAILURE = 'GET_SINGLE_FAILURE'
export const GET_PAGE_FAILURE = 'GET_PAGE_FAILURE'

export const TOGGLE_NAV = 'TOGGLE_NAV'

export const CLEAR_SINGLE = 'CLEAR_SINGLE'
const API_URL = '/api'
export const URL_ARTICLE = `${API_URL}/article`
export const ENTITIES_PER_PAGE = 10
