export const GET_INDEX_SUCCESS = 'GET_INDEX_SUCCESS'
export const GET_ARCHIVE_SUCCESS = 'GET_ARCHIVE_SUCCESS'
export const GET_SINGLE_SUCCESS = 'GET_SINGLE_SUCCESS'
export const GET_PAGE_SUCCESS = 'GET_PAGE_SUCCESS'
export const GET_YEARS_SUCCESS = 'GET_YEARS_SUCCESS'

export const GET_INDEX_FAILURE = 'GET_INDEX_FAILURE'
export const GET_ARCHIVE_FAILURE = 'GET_ARCHIVE_FAILURE'
export const GET_SINGLE_FAILURE = 'GET_SINGLE_FAILURE'
export const GET_PAGE_FAILURE = 'GET_PAGE_FAILURE'
export const GET_YEARS_FAILURE = 'GET_YEARS_FAILURE'

export const TOGGLE_TIME_SECTION = 'TOGGLE_TIME_SECTION'


export const TOGGLE_NAV = 'TOGGLE_NAV'

export const CLEAR_SINGLE = 'CLEAR_SINGLE'
export const URL_API = '/api'
export const URL_ARTICLE = `${URL_API}/article`
export const ENTITIES_PER_PAGE = 10
